//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Logic.MessagesModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public string Adress { get; set; }
        public bool IsSms { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public int tblMessageBatchId { get; set; }
    
        public virtual tblMessageBatch tblMessageBatch { get; set; }
    }
}
