//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Logic.MessagesModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSmsSenderDataProvider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string FromDisplayName { get; set; }
        public string FromPhoneNumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int MessageInterval { get; set; }
        public string SendProviderRestrictionDataJSON { get; set; }
        public string SendProviderRestrictionDataLogJSON { get; set; }
    }
}
