
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    public int Id { get; set; }

    public string UserNameEmail { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string House { get; set; }

    public string CellPhone { get; set; }

    public string FatherName { get; set; }

    public string FatherCellPhone { get; set; }

    public string MotherName { get; set; }

    public string MotherCellPhone { get; set; }

    public string FatherEmail { get; set; }

    public string MotherEmail { get; set; }

    public Nullable<int> schoolId { get; set; }

}

}
