
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblCalendar
{

    public int pk { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public string month { get; set; }

    public string HebMonth { get; set; }

    public string day { get; set; }

    public Nullable<bool> active { get; set; }

    public string @event { get; set; }

    public string HebDate { get; set; }

}

}
