
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblDictSystem
{

    public int id { get; set; }

    public string term { get; set; }

    public string CustomerTranslated { get; set; }

    public string SystemTranslated { get; set; }

    public string cultures { get; set; }

    public string status { get; set; }

    public Nullable<System.DateTime> DateCreatedUTC { get; set; }

    public Nullable<bool> cantBeChange { get; set; }

}

}
