
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmailSent
{

    public int pk { get; set; }

    public Nullable<int> itemInList { get; set; }

    public Nullable<int> familyId { get; set; }

    public string parent1Email { get; set; }

    public Nullable<bool> sentToParent1 { get; set; }

    public string parent2Email { get; set; }

    public Nullable<bool> sentToParent2 { get; set; }

    public string studentName { get; set; }

    public string studentId { get; set; }

    public string message { get; set; }

    public Nullable<System.DateTime> dateSent { get; set; }

    public Nullable<bool> statusParent1 { get; set; }

    public Nullable<bool> statusParent2 { get; set; }

    public string schoolName { get; set; }

    public Nullable<int> lineNumber { get; set; }

    public string comment { get; set; }

}

}
