
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblFamily
{

    public int familyId { get; set; }

    public string ParentId { get; set; }

    public string parent1Type { get; set; }

    public string parent1FirstName { get; set; }

    public string parent1LastName { get; set; }

    public string parent1Email { get; set; }

    public bool parent1EmailConfirm { get; set; }

    public bool parent1GetAlertByEmail { get; set; }

    public string parent1CellPhone { get; set; }

    public bool parent1CellConfirm { get; set; }

    public bool parent1GetAlertBycell { get; set; }

    public string parent2Type { get; set; }

    public string parent2FirstName { get; set; }

    public string parent2LastName { get; set; }

    public string parent2Email { get; set; }

    public Nullable<bool> parent2EmailConfirm { get; set; }

    public Nullable<bool> parent2GetAlertByEmail { get; set; }

    public string parent2CellPhone { get; set; }

    public Nullable<bool> parent2CellConfirm { get; set; }

    public Nullable<bool> parent2GetAlertBycell { get; set; }

    public System.DateTime date { get; set; }

    public Nullable<System.DateTime> LastUpdate { get; set; }

    public Nullable<bool> paymentOk { get; set; }

    public Nullable<System.DateTime> paymentDateConfirm { get; set; }

    public bool iAgree { get; set; }

    public Nullable<bool> subsidy { get; set; }

    public Nullable<bool> allredyUsed { get; set; }

    public bool oneParentOnly { get; set; }

    public string PaymentPlanID { get; set; }

    public string PaymentRequestID { get; set; }

    public bool registrationStatus { get; set; }

}

}
