
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblPaymentOrder
{

    public int PaymentOrderId { get; set; }

    public Nullable<int> FamilyId { get; set; }

    public string StudentId { get; set; }

    public Nullable<int> StudentPk { get; set; }

    public string FirstName { get; set; }

    public string LastNeme { get; set; }

    public string Email { get; set; }

    public string cellPhone { get; set; }

    public Nullable<int> schoolId { get; set; }

    public string AutorisationCode { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public string CCGateway { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public string CardToken { get; set; }

    public string CardExp { get; set; }

    public string PersonalId { get; set; }

    public string CardMask { get; set; }

    public string TxId { get; set; }

    public int Status { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public Nullable<int> PaymentRequestId { get; set; }

    public string paymentComment { get; set; }

}

}
