
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblStudent
{

    public int pk { get; set; }

    public int familyId { get; set; }

    public string studentId { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public int yearRegistration { get; set; }

    public string Shicva { get; set; }

    public string @class { get; set; }

    public string city { get; set; }

    public string street { get; set; }

    public int houseNumber { get; set; }

    public string zipCode { get; set; }

    public string CellPhone { get; set; }

    public Nullable<bool> CellConfirm { get; set; }

    public Nullable<bool> GetAlertByCell { get; set; }

    public string Email { get; set; }

    public Nullable<bool> EmailConfirm { get; set; }

    public Nullable<bool> GetAlertByEmail { get; set; }

    public Nullable<bool> paymentStatus { get; set; }

    public Nullable<System.DateTime> dateCreate { get; set; }

    public Nullable<System.DateTime> lastUpdate { get; set; }

    public bool registrationStatus { get; set; }

    public Nullable<bool> subsidy { get; set; }

    public string Color { get; set; }

    public Nullable<double> Lat { get; set; }

    public Nullable<double> Lng { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<double> distanceFromSchool { get; set; }

    public Nullable<bool> siblingAtSchool { get; set; }

    public Nullable<bool> specialRequest { get; set; }

    public string request { get; set; }

    public Nullable<int> cityId { get; set; }

    public Nullable<int> streetId { get; set; }

    public Nullable<int> schoolId { get; set; }

    public string schoolName { get; set; }

    public string AdminComment { get; set; }

    public Nullable<bool> payment3rdParty { get; set; }

    public string payment3rdPartyComment { get; set; }

}

}
