
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblSystem
{

    public int pk { get; set; }

    public string strKey { get; set; }

    public string strValue { get; set; }

    public string key { get; set; }

    public string value { get; set; }

    public Nullable<System.DateTime> LastModify { get; set; }

    public Nullable<int> ModifedBy { get; set; }

    public string strNamespace { get; set; }

}

}
