
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class ViewAlllinesByBusCompnyAndStation
{

    public long RowNum { get; set; }

    public string companyName { get; set; }

    public string LineNumber { get; set; }

    public string LineName { get; set; }

    public int Position { get; set; }

    public string StationName { get; set; }

    public Nullable<int> Direction { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<int> totalStudents { get; set; }

    public Nullable<System.TimeSpan> Duration { get; set; }

    public Nullable<System.DateTime> BasicArriveTime { get; set; }

    public Nullable<System.DateTime> BasicDepartureTime { get; set; }

    public string BusId { get; set; }

    public Nullable<int> seats { get; set; }

    public string PlateNumber { get; set; }

    public Nullable<double> price { get; set; }

    public Nullable<bool> Sun { get; set; }

    public Nullable<System.DateTime> SunTime { get; set; }

    public Nullable<bool> Mon { get; set; }

    public Nullable<System.DateTime> MonTime { get; set; }

    public Nullable<bool> Tue { get; set; }

    public Nullable<System.DateTime> TueTime { get; set; }

    public Nullable<bool> Wed { get; set; }

    public Nullable<System.DateTime> WedTime { get; set; }

    public Nullable<bool> Thu { get; set; }

    public Nullable<System.DateTime> ThuTime { get; set; }

    public Nullable<bool> Fri { get; set; }

    public Nullable<System.DateTime> FriTime { get; set; }

    public System.TimeSpan ArrivalDate { get; set; }

    public string Address { get; set; }

    public Nullable<int> StationType { get; set; }

    public Nullable<int> schoolId { get; set; }

    public string name { get; set; }

    public string adress { get; set; }

    public string city { get; set; }

}

}
