
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class ViewAllStudentFamilyLinesStation
{

    public int familyId { get; set; }

    public string studentId { get; set; }

    public string studentFirstName { get; set; }

    public string studentLastName { get; set; }

    public string Shicva { get; set; }

    public string @class { get; set; }

    public string city { get; set; }

    public string street { get; set; }

    public int houseNumber { get; set; }

    public string studentCellPhone { get; set; }

    public Nullable<bool> studentCellConform { get; set; }

    public Nullable<bool> studentGetAlertByCell { get; set; }

    public string studentEmail { get; set; }

    public Nullable<bool> studentEmailConfirm { get; set; }

    public Nullable<bool> studentGetAlertByEmail { get; set; }

    public bool registrationStatus { get; set; }

    public Nullable<bool> subsidy { get; set; }

    public string studentColor { get; set; }

    public Nullable<bool> studentActive { get; set; }

    public Nullable<double> distanceFromSchool { get; set; }

    public Nullable<bool> siblingAtSchool { get; set; }

    public string streetName { get; set; }

    public string cityName { get; set; }

    public string ParentId { get; set; }

    public string parent1Type { get; set; }

    public string parent1FirstName { get; set; }

    public string parent1LastName { get; set; }

    public string parent1Email { get; set; }

    public Nullable<bool> parent1EmailConfirm { get; set; }

    public Nullable<bool> parent1GetAlertByEmail { get; set; }

    public string parent1CellPhone { get; set; }

    public Nullable<bool> parent1GetAlertBycell { get; set; }

    public string parent2Type { get; set; }

    public string parent2FirstName { get; set; }

    public string parent2LastName { get; set; }

    public string parent2Email { get; set; }

    public Nullable<bool> parent2EmailConfirm { get; set; }

    public Nullable<bool> parent2GetAlertByEmail { get; set; }

    public string parent2CellPhone { get; set; }

    public Nullable<bool> parent2CellConfirm { get; set; }

    public Nullable<bool> parent2GetAlertBycell { get; set; }

    public Nullable<bool> paymentOk { get; set; }

    public Nullable<bool> subsidy_ { get; set; }

    public Nullable<bool> allredyUsed { get; set; }

    public Nullable<bool> familyRegistrationStatus { get; set; }

    public Nullable<int> distanceFromStation { get; set; }

    public string studentToLineColor { get; set; }

    public string LineName { get; set; }

    public string LineNumber { get; set; }

    public string lineColor { get; set; }

    public Nullable<int> Linedirection { get; set; }

    public Nullable<bool> lineIsActive { get; set; }

    public Nullable<System.TimeSpan> Duration { get; set; }

    public string StationName { get; set; }

    public Nullable<System.TimeSpan> ArrivalDate { get; set; }

    public Nullable<bool> Sun { get; set; }

    public Nullable<System.DateTime> SunTime { get; set; }

    public Nullable<bool> Mon { get; set; }

    public Nullable<System.DateTime> MonTime { get; set; }

    public Nullable<bool> Tue { get; set; }

    public Nullable<System.DateTime> TueTime { get; set; }

    public Nullable<bool> Wed { get; set; }

    public Nullable<System.DateTime> WedTime { get; set; }

    public Nullable<bool> Thu { get; set; }

    public Nullable<System.DateTime> ThuTime { get; set; }

    public Nullable<bool> Fri { get; set; }

    public Nullable<System.DateTime> FriTime { get; set; }

    public Nullable<bool> Sut { get; set; }

    public Nullable<System.DateTime> SutTime { get; set; }

    public Nullable<bool> specialRequest { get; set; }

    public string request { get; set; }

    public string schoolName { get; set; }

    public Nullable<int> StationType { get; set; }

    public Nullable<int> Position { get; set; }

    public Nullable<System.DateTime> BasicArriveTime { get; set; }

    public Nullable<System.DateTime> BasicDepartureTime { get; set; }

}

}
